[package]
name = "vesad"
version = "0.1.0"

[dependencies]
orbclient = "0.2"
ransid = "0.2"
rusttype = { version = "0.2", optional = true }
redox_syscall = { path = "../../syscall" }

[features]
default = []
