[package]
name = "e1000d"
version = "0.1.0"

[dependencies]
bitflags = "0.7"
netutils = { git = "https://github.com/redox-os/netutils.git" }
redox_event = { git = "https://github.com/redox-os/event.git" }
redox_syscall = "0.1"
