[package]
name = "ps2d"
version = "0.1.0"

[dependencies]
bitflags = "*"
orbclient = "0.2"
redox_event = { git = "https://github.com/redox-os/event.git" }
redox_syscall = { git = "https://github.com/redox-os/syscall.git" }
